server:
  port: 8080  # Gateway server port

spring:
  cloud:
    gateway:
      routes:
        - id: authentication-service
          uri: lb://authentication-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: ApiKey
            - name: JwtAuth
            
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: ApiKey
            - name: JwtAuth

management:
  endpoints:
    web:
      exposure:
        include: "*"