server:
  port: 8080  # Gateway server port

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - name: ApiKey
            - name: JwtAuth

management:
  endpoints:
    web:
      exposure:
        include: "*"